print("Welcome to Band Name Generator.")
city = input("Which city did you grow up in?\n")
pet = input("What is the name of a pet?\n")
print(f"Your band name could be {city} {pet}.")
print("Your band name could be " + city  + " " + pet + ".\n")